name: notes_app
description: "A complete Flutter Notes App with advanced features"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^19.4.2
  firebase_core: ^4.1.0
  cloud_firestore: ^6.0.1
  firebase_auth: ^6.0.2
  firebase_storage: ^13.0.1
  timezone: ^0.10.0
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  cached_network_image: ^3.3.0
  http: ^1.5.0
  intl: ^0.20.2
  image_picker: ^1.0.4
  file_picker: ^10.3.3
  image_cropper: ^10.0.0+1
  flutter_launcher_icons: ^0.14.4
  provider: ^6.1.1
  flutter_dotenv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"